---
title: "Predict Overall Survival Length in Breast Cancer patients using Proteomic Data"
author: "Ngoc Duong - nqd2000"
date: "3/22/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(caret)
library(tidyverse)
library(data.table)
library(viridis)
library(splines)
library(mgcv)
library(ggplot2)
library(pdp)
library(earth)
library(patchwork)
library(nnet)
library(janitor)
library(FNN)
library(ModelMetrics)
library(caret)
library(boot)
library(microbenchmark)
library(broom)
library(corrplot)
library(pls)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

Import data
```{r}
outcome = read.csv("./breastcancerproteomes/clinical_data_breast_cancer.csv") %>% janitor::clean_names()
proteome = read.csv("./breastcancerproteomes/77_cancer_proteomes_CPTAC_itraq.csv") 

#clean proteome data
#transpose dataset
proteome_tp <- transpose(proteome)

#get row and colnames in order
colnames(proteome_tp) <- proteome$RefSeq_accession_number
proteome_tp$par_id <- colnames(proteome) 

#rearrange data
proteome_clean = as_tibble(proteome_tp) %>% select(par_id, everything()) 

proteome_final = proteome_clean[-c(1:3),] %>% 
  separate(par_id, c("id2","id4","tcga")) %>% #sep id based on 2-digit id and 4-digit id
  select(-tcga)

#clean outcome data 
outcome_clean = outcome %>% 
  filter(gender == "FEMALE") %>% #filter out 1 obs that is male
  separate(complete_tcga_id, c("tcga","id2","id4"), "-") %>% #sep id based on 2-digit id and 4-digit id
  select(-tcga) %>% 
  select(id2, id4, os_time)

#merge data 
bcp_data = left_join(proteome_final, outcome_clean, by = c("id2", "id4"))

bcp_data$os_time = ifelse(bcp_data$os_time == 0, 1e-24, bcp_data$os_time)

bcp_data = bcp_data %>% 
  mutate(log_os = log(os_time)) %>% 
  select(-os_time) %>% 
  drop_na(log_os) 

#only looking at complete cases/get rid of proteins that miss quantification values
missing.counts <- 0
for(i in 1:ncol(bcp_data)){
missing.counts[i] <- sum(is.na(bcp_data[,i]))}
a <- names(bcp_data)[which(missing.counts > 0)] 

#final data
bcp_final = bcp_data[ ,!(colnames(bcp_data) %in% c(a))] %>% 
  select(-id2, -id4)
```


Use PCR
```{r}
#use train function in caret 
set.seed(7)
trRows <- createDataPartition(bcp_final$log_os,
                              p = 0.75,
                              list = FALSE)

#training data 
x <- model.matrix(log_os ~., bcp_final)[trRows, -1]
y <- bcp_final$log_os[trRows]

#test data
x2 <- model.matrix(log_os~., bcp_data)
y2 <- bcp_final$log_os[-trRows]

library(pls)
pcr_mod <- pcr(log_os ~., 
               data = bcp_final[trRows,],
               scale = TRUE,
               validation = "CV")
validationplot(pcr.mod, val.type = "MSEP",legendpos = "topright")

x_train = bcp_final %>% select(-log_os)

set.seed(7)
ctrl1 <-trainControl(method = "repeatedcv", number = 10, repeats = 5)
pcr_fit <-train(x_train, bcp_final$log_os,
                method = "pcr",
                tuneGrid = data.frame(ncomp = 1:200),
                trControl = ctrl1,
                scale = TRUE)
plot(pcr_fit)
```


